### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/vcztools#3]
It would be good to copy across some of the tests for the VCF writing code from sgkit. Hopefully we can do some easy round-trip tests using bio2zarr?

@tomwhite, what would be involved here?

**Comment by tomwhite** [comment]
I think we can copy them over - I can do that.

It's possible that we will run into https://github.com/sgkit-dev/vcf-zarr-spec/issues/11, but perhaps we change `assert_vcfs_close` to be more lenient in cases like that.

**Comment by jeromekelleher** [comment]
That sounds like a great plan, thanks @tomwhite!
