### ISSUE TITLE
Move to sgkit-dev?

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/vcztools#42]
Shall we move to sgkit-dev so we can reduce the bus-factor @tomwhite? I'll be away for a few weeks and I don't want to block you and others from contributing.

**Comment by jeromekelleher** [comment]
Whoops, forgot about #30

**Comment by tomwhite** [comment]
> Shall we move to sgkit-dev so we can reduce the bus-factor @tomwhite? I'll be away for a few weeks and I don't want to block you and others from contributing.

+1
